AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  SamShipsTable:
    Type: AWS::Serverless::SimpleTable
  SamShipsWebAPI:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: dotnetcore3.1
      Handler: SamShips.WebAPI::SamShips.WebAPI.LambdaEntryPoint::FunctionHandlerAsync
      CodeUri: s3://nino-aws-learning-bucket/898a1b630eaed8bf5ab13e85f618c4b6
      MemorySize: 256
      Timeout: 30
      Environment:
        Variables:
          TABLE_NAME:
            Ref: SamShipsTable
      Policies: AmazonDynamoDBFullAccess
      Events:
        GetShipsResource:
          Type: Api
          Properties:
            Path: /ships
            Method: get
        PostShipsResource:
          Type: Api
          Properties:
            Path: /ships
            Method: post
        Ship:
          Type: Api
          Properties:
            Path: /ships/{id}
            Method: any
  SamShipsHeartbeat:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: dotnetcore3.1
      Handler: SamShips.Heartbeat::SamShips.Heartbeat.Entrypoint::Handler
      CodeUri: s3://nino-aws-learning-bucket/c876fe6cf14ccdb03816fd856adf91c8
      Environment:
        Variables:
          TABLE_NAME:
            Ref: SamShipsTable
      Policies: AmazonDynamoDBFullAccess
