AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  SamShipsTable:
    Type: AWS::Serverless::SimpleTable
  SamShipsWebAPI:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: dotnetcore3.1
      Handler: SamShips.WebAPI::SamShips.WebAPI.LambdaEntryPoint::FunctionHandlerAsync
      CodeUri: s3://nino-aws-learning-bucket/9053e27adb2b79af7d1b83245a608a2d
      MemorySize: 256
      Timeout: 30
      Environment:
        Variables:
          TABLE_NAME:
            Ref: SamShipsTable
      Policies: AmazonDynamoDBFullAccess
      Events:
        Ships:
          Type: Api
          Properties:
            Path: /ships
            Method: any
        SingleShip:
          Type: Api
          Properties:
            Path: /ships/{id}
            Method: any
  SamShipsHeartbeat:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: dotnetcore3.1
      Handler: SamShips.Heartbeat::SamShips.Heartbeat.Entrypoint::Handler
      CodeUri: s3://nino-aws-learning-bucket/0c57e1a1bf3281f3757c4b8514f3472d
      Environment:
        Variables:
          TABLE_NAME:
            Ref: SamShipsTable
      Policies: AmazonDynamoDBFullAccess
