/**
 * SamShips.WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type Orders = 'Docked' | 'Trading' | 'Piracy' | 'Enforcement';

export const Orders = {
    Docked: 'Docked' as Orders,
    Trading: 'Trading' as Orders,
    Piracy: 'Piracy' as Orders,
    Enforcement: 'Enforcement' as Orders
};