/**
 * SamShips.WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export const Regions = ['Africa', 'Antarctica', 'Asia', 'Australia', 'Europe', 'NorthAmerica', 'SouthAmerica'] as const;
export type Region = 'Africa' | 'Antarctica' | 'Asia' | 'Australia' | 'Europe' | 'NorthAmerica' | 'SouthAmerica';

export const Region = {
    Africa: 'Africa' as Region,
    Antarctica: 'Antarctica' as Region,
    Asia: 'Asia' as Region,
    Australia: 'Australia' as Region,
    Europe: 'Europe' as Region,
    NorthAmerica: 'NorthAmerica' as Region,
    SouthAmerica: 'SouthAmerica' as Region
};