/**
 * SamShips.WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Int64Property } from './int64Property';
import { Orders } from './orders';
import { Region } from './region';
import { ShipClass } from './shipClass';

export class Ship { 
    id?: string;
    name?: string;
    class?: ShipClass;
    location?: Region;
    orders?: Orders;
    hull?: Int64Property;
    cargo?: { [key: string]: number; };
    cargoCapacity?: number;
}